### PR TITLE
[T23] Setup API and empty routes

### PR DESCRIPTION
**Pull request by absirgue**
Worked on T23:
- established a way to connect API to DB hosted on remote VPS
- created all the empty routes

Tested the connection and routes manually using Postman.

### CODE REVIEW

**Comment by TunaAtasayar** [comment]
Very well done!

**Review by TunaAtasayar — APPROVED** [review]
very well done, the logins are hidden.

**Review by Ali-Alkhars — APPROVED** [review]
Well done Anton! I have nothing more to add. You could mark this ticket as done

**Review by Ali-Alkhars — APPROVED** [review]
GitHub wants me to approve again, so here I am approving again.

**Pull request merged**
